CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(20) DEFAULT 'farmer',
  "company_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "sessions" (
  "id" varchar(128) PRIMARY KEY,
  "user_id" int NOT NULL,
  "expires_at" timestamp NOT NULL,
  "ip_address" varchar(45),
  "created_at" timestamp
);

CREATE TABLE "company" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar(255) NOT NULL,
  "telephone" varchar(20),
  "code_postal" varchar(10),
  "country" varchar(100),
  "created_at" timestamp
);

CREATE TABLE "farm" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar(255) NOT NULL,
  "company_id" int NOT NULL,
  "adresse" varchar(255),
  "code_postal" varchar(10),
  "country" varchar(100),
  "created_at" timestamp
);

CREATE TABLE "parcelle" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farm_id" int NOT NULL,
  "nom" varchar(255) NOT NULL,
  "superficie_ha" decimal(10,2),
  "culture_type" varchar(100),
  "position_lat" decimal(10,7),
  "position_lng" decimal(10,7),
  "created_at" timestamp
);

CREATE TABLE "kit" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parcelle_id" int NOT NULL,
  "nom" varchar(255),
  "modele" varchar(100),
  "date_installation" timestamp,
  "actif" boolean DEFAULT true,
  "created_at" timestamp
);

CREATE TABLE "capteur" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kit_id" int NOT NULL,
  "type" varchar(50),
  "unite" varchar(20),
  "actif" boolean DEFAULT true,
  "position_lat" decimal(10,7),
  "position_lng" decimal(10,7),
  "created_at" timestamp
);

CREATE TABLE "mesure" (
  "time" timestamp NOT NULL,
  "capteur_id" int NOT NULL,
  "valeur" decimal(10,4) NOT NULL,
  "qualite" smallint DEFAULT 1
);

CREATE TABLE "recolte" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parcelle_id" int NOT NULL,
  "date_recolte" date NOT NULL,
  "culture_type" varchar(100),
  "quantite_kg" decimal(10,2),
  "qualite_note" smallint,
  "commentaire" text,
  "created_at" timestamp
);

CREATE TABLE "photo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url_path" varchar(500) NOT NULL,
  "entity_type" varchar(50),
  "entity_id" int NOT NULL,
  "uploaded_by" int,
  "uploaded_at" timestamp
);

CREATE TABLE "culture" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar(60) UNIQUE NOT NULL,
  "icon" varchar(10),
  "soil_min" smallint,
  "soil_max" smallint,
  "temp_min" smallint,
  "temp_max" smallint,
  "hum_air_min" smallint,
  "hum_air_max" smallint,
  "besoin_eau" varchar(20),
  "besoin_soleil" varchar(20)
);

CREATE TABLE "camera" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farm_id" int,
  "nom" varchar(150) NOT NULL,
  "emplacement" varchar(150),
  "url" varchar(500) NOT NULL,
  "thumbnail" varchar(500),
  "icon" varchar(10),
  "statut" varchar(20) DEFAULT 'live',
  "created_at" timestamp
);

COMMENT ON COLUMN "users"."role" IS 'admin | farmer | viewer';

COMMENT ON COLUMN "parcelle"."superficie_ha" IS 'hectares';

COMMENT ON COLUMN "parcelle"."culture_type" IS 'blé, maïs, vigne...';

COMMENT ON COLUMN "parcelle"."position_lat" IS 'GPS latitude';

COMMENT ON COLUMN "parcelle"."position_lng" IS 'GPS longitude';

COMMENT ON COLUMN "kit"."nom" IS 'ex: Kit Nord-Est';

COMMENT ON COLUMN "kit"."modele" IS 'ex: TechFarm v1';

COMMENT ON COLUMN "capteur"."type" IS 'temperature | humidite_air | humidite_sol | luminosite | ph | qualite_air | debit_eau';

COMMENT ON COLUMN "capteur"."unite" IS '°C, %, lux, pH...';

COMMENT ON COLUMN "mesure"."time" IS 'hypertable TimescaleDB';

COMMENT ON COLUMN "mesure"."qualite" IS '1:ok | 0:suspect | -1:erreur';

COMMENT ON COLUMN "recolte"."qualite_note" IS '1 à 5';

COMMENT ON COLUMN "photo"."url_path" IS 'URL MinIO';

COMMENT ON COLUMN "photo"."entity_type" IS 'parcelle | kit | recolte | farm';

ALTER TABLE "users" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "farm" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "parcelle" ADD FOREIGN KEY ("farm_id") REFERENCES "farm" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "kit" ADD FOREIGN KEY ("parcelle_id") REFERENCES "parcelle" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "capteur" ADD FOREIGN KEY ("kit_id") REFERENCES "kit" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mesure" ADD FOREIGN KEY ("capteur_id") REFERENCES "capteur" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recolte" ADD FOREIGN KEY ("parcelle_id") REFERENCES "parcelle" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "camera" ADD FOREIGN KEY ("farm_id") REFERENCES "farm" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "photo" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
