import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/theme';

export const st = StyleSheet.create({
  root: { flex: 1, flexDirection: 'column', backgroundColor: COLORS.background, position: 'relative' },

  navbar: { height: 64, flexDirection: 'row', alignItems: 'center', backgroundColor: '#0d1520', borderBottomWidth: 1, borderBottomColor: COLORS.border, paddingHorizontal: 24 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 10, width: 190 },
  brandIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#1a3a1a', alignItems: 'center', justifyContent: 'center' },
  brandTxt: { color: COLORS.text, fontSize: 17, fontWeight: 'bold', letterSpacing: 0.5 },
  navTabs: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4 },
  navTabWrap: { alignItems: 'center', paddingHorizontal: 14 },
  navTab: { color: COLORS.textSecondary, fontSize: 14 },
  navTabOn: { color: COLORS.text, fontWeight: '600' },
  navUnderline: { height: 2, backgroundColor: COLORS.accent, borderRadius: 1, marginTop: 4, width: '100%' },
  navSep: { color: COLORS.border, fontSize: 18 },
  navRight: { flexDirection: 'row', alignItems: 'center', gap: 10, width: 260, justifyContent: 'flex-end' },
  avatarGuest: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#1e2d3d', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#334' },
  navGuestLabel: { color: COLORS.textSecondary, fontSize: 12 },
  loginBtn: { backgroundColor: COLORS.accent, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 7 },
  loginBtnTxt: { color: '#fff', fontSize: 12, fontWeight: '600' },
  navUserEmail: { color: COLORS.text, fontSize: 12, fontWeight: '600', maxWidth: 150 },
  navUserRole: { color: COLORS.accent, fontSize: 10, marginTop: 1 },
  navDiv: { width: 1, height: 20, backgroundColor: COLORS.border },
  userBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, borderWidth: 1, borderColor: COLORS.accent + '33', backgroundColor: '#1a2535' },
  userBtnActive: { borderColor: COLORS.accent + '88', backgroundColor: '#243047' },
  chevron: { color: COLORS.textSecondary, fontSize: 10, marginLeft: 2 },
  bellBtn: { width: 36, height: 36, borderRadius: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: COLORS.accent + '33', backgroundColor: '#1a2535' },
  bellBtnActive: { borderColor: COLORS.accent + '88', backgroundColor: '#243047' },
  bellIcon: { fontSize: 17 },
  notifsDropdown: { position: 'absolute', top: 64, right: 220, width: 300, backgroundColor: '#0e1929', borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, zIndex: 200, shadowColor: '#000', shadowOpacity: 0.6, shadowRadius: 24, shadowOffset: { width: 0, height: 8 } },
  notifsHeader: { paddingHorizontal: 16, paddingVertical: 14 },
  notifsTitle: { color: COLORS.text, fontSize: 14, fontWeight: '700' },
  notifsEmpty: { alignItems: 'center', paddingVertical: 36, gap: 8 },
  notifsEmptyIcon: { fontSize: 32 },
  notifsEmptyTxt: { color: COLORS.text, fontSize: 14, fontWeight: '600' },
  notifsEmptySub: { color: COLORS.textSecondary, fontSize: 12 },
  menuOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 100 },
  dropdown: { position: 'absolute', top: 64, right: 24, width: 270, backgroundColor: '#0e1929', borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, zIndex: 200, shadowColor: '#000', shadowOpacity: 0.6, shadowRadius: 24, shadowOffset: { width: 0, height: 8 } },
  dropdownHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16 },
  dropdownAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#1e2d3d', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: COLORS.accent + '66' },
  dropdownEmail: { color: COLORS.text, fontSize: 13, fontWeight: '700' },
  dropdownRole: { color: COLORS.accent, fontSize: 11, marginTop: 2 },
  dropdownDiv: { height: 1, backgroundColor: COLORS.border, marginHorizontal: 12 },
  dropdownItem: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 13 },
  dropdownItemTxt: { color: COLORS.text, fontSize: 13, fontWeight: '500' },
  dropdownItemSub: { color: COLORS.textSecondary, fontSize: 11, marginTop: 1 },
  dropdownArrow: { color: COLORS.textSecondary, fontSize: 18 },
  dropdownLogoutItem: { marginBottom: 4 },
  dropdownLogoutTxt: { color: '#e74c3c', fontSize: 13, fontWeight: '600', flex: 1 },

  body: { flex: 1, flexDirection: 'row' },

  left: { width: 200, flexShrink: 0, flexGrow: 0, backgroundColor: '#0d1520', borderRightWidth: 1, borderRightColor: COLORS.border, paddingTop: 16, paddingHorizontal: 12, paddingBottom: 12, flexDirection: 'column' },
  sideSecLabel: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.8, paddingHorizontal: 4 },
  secLabel: { color: COLORS.text, fontSize: 15, fontWeight: '700', marginBottom: 10, marginTop: 4 },
  pageBtn: { backgroundColor: '#1e2d3d', borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  pageBtnTxt: { color: COLORS.text, fontSize: 12, fontWeight: '700' },
  sideNav: { gap: 2 },
  sideNavItem: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 8 },
  sideNavItemActive: { backgroundColor: COLORS.accent },
  sideNavIcon: { fontSize: 16, width: 20, textAlign: 'center', color: COLORS.accent },
  sideNavIconActive: { color: '#fff' },
  sideNavLabel: { color: COLORS.textSecondary, fontSize: 13, fontWeight: '500' },
  sideNavLabelActive: { color: '#fff', fontWeight: '700' },
  sideCondCard: { backgroundColor: '#0a1422', borderRadius: 10, borderWidth: 1, borderColor: COLORS.border, padding: 12, marginBottom: 8 },
  sideCondRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  sideCondIco: { fontSize: 18, width: 24, textAlign: 'center', color: COLORS.textSecondary },
  sideCondVal: { color: COLORS.text, fontSize: 15, fontWeight: '700' },
  sideCondSub: { color: COLORS.textSecondary, fontSize: 11, marginTop: 1 },
  sideMajCard: { backgroundColor: '#0a1422', borderRadius: 8, borderWidth: 1, borderColor: COLORS.border, padding: 10 },
  sideMajLabel: { color: COLORS.textSecondary, fontSize: 10, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
  sideMajDate: { color: COLORS.text, fontSize: 12, fontWeight: '600', marginTop: 3 },

  center: { flex: 1, flexDirection: 'column', backgroundColor: '#080f18', padding: 12, gap: 12 },
  mapCard: { flex: 1, borderRadius: 14, overflow: 'hidden', borderWidth: 1, borderColor: COLORS.border },
  farmHdr: { height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, backgroundColor: '#0d1520', borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, zIndex: 50, overflow: 'visible' },
  farmNameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  farmDot: { width: 10, height: 10, borderRadius: 5 },
  farmName: { color: COLORS.text, fontSize: 17, fontWeight: 'bold' },
  farmPickerBtn: { flexDirection: 'row', alignItems: 'center' },
  farmDropdown: {
    position: 'absolute',
    top: 30,
    left: 0,
    backgroundColor: '#0e1929',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    minWidth: 200,
    zIndex: 300,
    boxShadow: '0 4px 16px rgba(0,0,0,0.5)',
  },
  farmDropdownItem: { paddingHorizontal: 16, paddingVertical: 11 },
  farmDropdownItemActive: { backgroundColor: COLORS.accent + '22' },
  farmDropdownText: { color: COLORS.textSecondary, fontSize: 14 },
  farmDropdownTextActive: { color: COLORS.accent, fontWeight: '700' },

  camOverlay: { position: 'absolute', top: 14, left: 14, width: 165, zIndex: 10 },
  camFeed: { height: 105, borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: '#555' },
  liveBadge: { position: 'absolute', top: 7, left: 7, flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#e74c3c', paddingHorizontal: 5, paddingVertical: 2, borderRadius: 3, zIndex: 11 },
  liveDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#fff' },
  liveTxt: { color: '#fff', fontSize: 9, fontWeight: 'bold' },
  camLabelBar: { backgroundColor: 'rgba(0,0,0,0.8)', paddingVertical: 5, paddingHorizontal: 10, borderBottomLeftRadius: 8, borderBottomRightRadius: 8 },
  camLabelTxt: { color: '#fff', fontSize: 11, textAlign: 'center' },

  alertPin: { position: 'absolute', backgroundColor: '#e74c3c', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 5, zIndex: 10 },
  alertPinTxt: { color: '#fff', fontSize: 11, fontWeight: '600' },
  pin: { position: 'absolute', fontSize: 20, zIndex: 8 },
  blueDot: { position: 'absolute', width: 10, height: 10, borderRadius: 5, backgroundColor: '#3498db', zIndex: 8 },
  tempBadge: { position: 'absolute', bottom: 14, left: '40%', backgroundColor: 'rgba(0,0,0,0.82)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: '#e67e22', zIndex: 10 },
  tempTxt: { color: '#e67e22', fontSize: 16, fontWeight: 'bold' },

  chartsRow: { flexDirection: 'row', height: 175 },
  chartCard: { paddingTop: 10, borderRadius: 10, borderWidth: 1, borderColor: COLORS.border, backgroundColor: '#0d1520', overflow: 'hidden' },
  chartHdr: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, marginBottom: 6, gap: 6 },
  chartTitle: { color: COLORS.text, fontSize: 12, fontWeight: '600', flex: 1 },
  chartLegend: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  lDot: { width: 7, height: 7, borderRadius: 4 },
  lTxt: { color: COLORS.textSecondary, fontSize: 10 },
  chartBtns: { flexDirection: 'row', gap: 2 },
  chartBtn: { width: 18, height: 18, borderRadius: 3, backgroundColor: COLORS.surface, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: COLORS.border },
  chartBtnTxt: { color: COLORS.textSecondary, fontSize: 8 },
  axisLbl: { color: COLORS.textSecondary, fontSize: 9 },
  soilBadge: { position: 'absolute', right: 10, bottom: 12, backgroundColor: '#e74c3c', paddingHorizontal: 5, paddingVertical: 2, borderRadius: 3 },
  soilBadgeTxt: { color: '#fff', fontSize: 10, fontWeight: 'bold' },

  // ─── New chart styles
  chartUnit: { color: COLORS.textSecondary, fontSize: 10 },
  chartCardSoil: { width: 270, borderLeftWidth: 1, borderLeftColor: COLORS.border },
  soilGaugeRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingBottom: 8 },
  soilLegend: { flex: 1, gap: 10, marginLeft: 8 },
  soilLegItem: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  soilLegDot: { width: 10, height: 10, borderRadius: 5 },
  soilLegTxt: { color: COLORS.textSecondary, fontSize: 11 },

  // ─── KPI cards
  kpiRow: { flexDirection: 'row', gap: 10 },
  kpiCard: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#0d1520', borderRadius: 10, borderWidth: 1, borderColor: COLORS.border, padding: 14 },
  kpiIconWrap: { width: 44, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  kpiIcon: { fontSize: 22 },
  kpiValue: { color: COLORS.text, fontSize: 22, fontWeight: '800', lineHeight: 26 },
  kpiLabel: { color: COLORS.textSecondary, fontSize: 11, marginTop: 1 },
  kpiSub: { fontSize: 11, fontWeight: '600', marginTop: 3 },

  right: { width: 220, flexShrink: 0, flexGrow: 0, backgroundColor: '#0d1520', borderLeftWidth: 1, borderLeftColor: COLORS.border, padding: 12 },
  alertCard: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 8, backgroundColor: '#131e2e', borderRadius: 9, borderLeftWidth: 3, padding: 9 },
  alertIco: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  alertTitle: { color: COLORS.text, fontSize: 12, fontWeight: '600' },
  alertSub: { color: COLORS.textSecondary, fontSize: 10, marginTop: 2 },
  div: { height: 1, backgroundColor: COLORS.border, marginVertical: 10 },
  actRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 7 },
  actTitle: { color: COLORS.text, fontSize: 11, fontWeight: '600' },
  actTime: { color: COLORS.textSecondary, fontSize: 9 },

  // ─── Extra page styles ────────────────────────────────────────
  pagePad:  { flex: 1, padding: 24, backgroundColor: '#080f18' },
  pageHdr:  { marginBottom: 20 },
  pageTitle:{ color: COLORS.text, fontSize: 22, fontWeight: '800' },
  pageSub:  { color: COLORS.textSecondary, fontSize: 13, marginTop: 4 },

  farmGrid:     { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  farmGridCard: { width: 280, backgroundColor: '#0d1520', borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, padding: 16 },
  farmStatChip: { flex: 1, backgroundColor: '#080f18', borderRadius: 8, padding: 10, alignItems: 'center' },
  farmStatVal:  { color: COLORS.text, fontSize: 18, fontWeight: '800' },
  farmStatLbl:  { color: COLORS.textSecondary, fontSize: 10, marginTop: 2 },

  filterChip:       { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20, borderWidth: 1, borderColor: COLORS.border, backgroundColor: '#0d1520' },
  filterChipActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
  filterChipTxt:    { color: COLORS.textSecondary, fontSize: 12, fontWeight: '600' },
  filterChipTxtActive: { color: '#fff' },

  tableCard:   { backgroundColor: '#0d1520', borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, overflow: 'hidden', marginBottom: 14 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#0a1422', paddingHorizontal: 16, paddingVertical: 10 },
  tableHd:     { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  tableRow:    { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 12, alignItems: 'center' },
  tableTd:     { color: COLORS.textSecondary, fontSize: 12 },

  histRow:  { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 18 },
  histTime: { width: 55, fontSize: 12, fontWeight: '600', textAlign: 'right' },
  histDot:  { width: 10, height: 10, borderRadius: 5, flexShrink: 0 },

  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 60 },
  emptyIco:   { fontSize: 48, marginBottom: 12 },
  emptyTxt:   { color: COLORS.textSecondary, fontSize: 16 },

  settingsSectionLbl: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 4 },

  // ─── Camera sidebar widget
  camSideCard: { backgroundColor: '#070e19', borderRadius: 10, borderWidth: 1, borderColor: '#1a2a3a', padding: 10, marginTop: 12 },
  camSideLivePill: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(231,76,60,0.12)', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 5, borderWidth: 1, borderColor: 'rgba(231,76,60,0.3)' },
  camSidePreview: { height: 90, borderRadius: 8, backgroundColor: '#020508', borderWidth: 1, borderColor: '#0e1e2e', overflow: 'hidden', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  camSideScanGrid: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, opacity: 0.06, backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 3px, rgba(255,255,255,0.8) 3px, rgba(255,255,255,0.8) 4px)' },
  camSideTimestamp: { position: 'absolute', bottom: 5, left: 7 },
  camBracket: { position: 'absolute', width: 10, height: 10, borderColor: 'rgba(46,204,113,0.6)' },

  // ─── Camera page
  camCard: { width: 300, backgroundColor: '#0d1520', borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, overflow: 'hidden' },
  camThumbWrap: { height: 170, backgroundColor: '#0a1422', position: 'relative' },
  camThumbOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 2 },
  camLivePill: { position: 'absolute', top: 10, left: 10, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(0,0,0,0.75)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, zIndex: 3, borderWidth: 1, borderColor: '#e74c3c55' },
  camPlayBtn: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', zIndex: 4 },

  // Parcelle map overlays  mapNoGps: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0d1520cc' },
  mapNoGpsTxt: { color: COLORS.textSecondary, fontSize: 13 },
  parcelleNav: { position: 'absolute', bottom: 14, alignSelf: 'center', left: '50%', transform: [{ translateX: -110 }], width: 220, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: 'rgba(13,21,32,0.9)', borderRadius: 22, borderWidth: 1, borderColor: COLORS.border, paddingVertical: 5, paddingHorizontal: 8 },
  parcelleNavBtn: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: '#1e2d3d' },
  parcelleNavArrow: { color: COLORS.text, fontSize: 22, fontWeight: 'bold', lineHeight: 26 },
  parcelleNavLabel: { color: COLORS.text, fontSize: 11, fontWeight: '600', flex: 1, textAlign: 'center' },

  // Filtre capteurs (overlay carte)
  sensorFilterBar: { position: 'absolute', top: 10, left: 10, right: 10, flexDirection: 'row', flexWrap: 'wrap', gap: 6, zIndex: 500 },
  sensorChip: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(13,21,32,0.92)', borderWidth: 1, borderColor: COLORS.border, borderRadius: 14, paddingHorizontal: 9, paddingVertical: 4 },
  sensorChipOff: { opacity: 0.5 },
  sensorChipTxt: { color: COLORS.text, fontSize: 11, fontWeight: '600' },
  sensorChipAll: { backgroundColor: 'rgba(39,174,96,0.9)', borderColor: '#27ae60' },
  sensorChipAllTxt: { color: '#fff', fontSize: 11, fontWeight: '700' },

  // Modal ajouter caméra
  modalOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.6)', alignItems: 'center', justifyContent: 'center', zIndex: 9999 },
  modalCard: { width: 420, maxWidth: '90%', backgroundColor: '#0d1520', borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, padding: 22 },
  modalLabel: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: 6, marginTop: 12 },
  modalInput: { backgroundColor: '#0a1422', borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, color: COLORS.text, fontSize: 13 },
  modalBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 11, borderRadius: 8 },
  modalBtnCancel: { backgroundColor: '#1e2d3d' },
  modalBtnOk: { backgroundColor: COLORS.accent },
});
